name: auto_mappr
description: Code generation for mapping between different objects with ease.
version: 2.5.0
repository: https://github.com/netglade/auto_mappr
issue_tracker: https://github.com/netglade/auto_mappr/issues
screenshots:
  - description: The auto_mappr package logo.
    path: doc/icon.png

environment:
  sdk: ^3.0.0

dependencies:
  # TODO: Support analyzer same way as json_serializable https://github.com/google/json_serializable.dart/pull/1333
  analyzer: ^7.2.0
  auto_mappr_annotation: ^2.2.0
  build: ^2.4.2
  built_collection: ^5.1.1
  code_builder: ^4.10.1
  collection: ^1.19.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  meta: ^1.8.0
  path: ^1.9.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  generator_test: 
     git: https://github.com/the-best-is-best/generator_test
  mocktail: ^1.0.4
  netglade_analysis: ^15.0.0
  source_gen_test: ^1.1.1
  test: ^1.25.14
